apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-app
  template:
    metadata:
      labels:
        app: flask-app
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: flask-app
        image: aycaakyol3/flask-app-web:latest
        ports:
        - containerPort: 7001
        env:
        - name: FLASK_ENV
          value: "development"
        - name: DB_HOST
          value: "room-management.crym2c22ug8h.us-east-1.rds.amazonaws.com"
        - name: DB_NAME
          value: "postgres"
        - name: DB_USER
          value: "postgres"
        - name: DB_PASSWORD
          value: "bbm473room"
---
apiVersion: v1
kind: Service
metadata:
  name: flask-app-service
spec:
  type: NodePort
  ports:
  - port: 7001
    targetPort: 7001
    nodePort: 30001
  selector:
    app: flask-app
