version: '3.8'

services:
  web:
    build: .
    container_name: flask-app
    ports:
      - "7001:7001"
    environment:
      - FLASK_ENV=development
      - DB_HOST=room-management.crym2c22ug8h.us-east-1.rds.amazonaws.com
      - DB_NAME=postgres
      - DB_USER=postgres
      - DB_PASSWORD=bbm473room
    depends_on:
      - db

  db:
    image: postgres:16.1
    container_name: postgres-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
